name: generate-snake

on:
  schedule:
      - cron: "0 0 * * *"
   workflow_dispatch:
   
permissions:
  contents: write
  
  jobs:
    snake:
      runs-on: ubuntu-latest
      
      steps:
        - name: Generate snake
          uses: Platane/snk@v3
          with:
            github_user_name: miidhunraj
            outputs: |
              dist/snake.svg
              dist/snake-dark.svg
              
        - name: Deploy snake
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
            publish_branch: output
            
